### ISSUE TITLE
support Thumbnail Saved?

### ISSUE THREAD

**Issue by sasangeo** [Itz-fork/Unzipper-Bot#12]
Add thumbnail support in unzip bot

**Comment by EDM115** [comment]
Currently working on it in my own version
It half works, will keep you up to date

https://github.com/EDM115/unzip-bot/issues/27

**Comment by Itz-fork** [comment]
Sorry for noticing your request / suggestion late. For now [I added](https://github.com/Itz-fork/Unzipper-Bot/commit/64f0ffce8975439164797a36a20e27bf62c8fddb) a thumbnail system using private telegram channel as database

**Comment by EDM115** [comment]
> Currently working on it in my own version It half works, will keep you up to date
  
As [Dan said](https://github.com/pyrogram/pyrogram/issues/1014?notification_referrer_id=NT_kwDOBON1bLMzNzc1MDc1MDg2OjgyMDE1NTk2#event-6818798266), some Files can't have their own custom thumb due to telegram API  
Solution might be to use individual methods (send_audio, send_photo, …) based on file extension recognizing, which should work better  
Plus, some documents unexpectedly can't have any thumbnail, but it's telegram side problem

**Comment by Itz-fork** [comment]
> As [Dan said](https://github.com/pyrogram/pyrogram/issues/1014?notification_referrer_id=NT_kwDOBON1bLMzNzc1MDc1MDg2OjgyMDE1NTk2#event-6818798266), some Files can't have their own custom thumb due to telegram API Solution might be to use individual methods (send_audio, send_photo, …) based on file extension recognizing, which should work better Plus, some documents unexpectedly can't have any thumbnail, but it's telegram side problem

Yes. Sometimes telegram won't use the thumbnail we provide, instead it either generates a thumbnail or just no thumbnail at all (happens with both `send_video` and `send_document` functions). Aside from that, I'm not sure using the methods related to the file type (`send_audio`, `send_animation`) will do much of a difference.
